[2024-11-06T19:47:15.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T19:47:15.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-06T19:47:15.185+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-06T19:47:15.187+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-06T19:47:15.232+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-05-10 00:00:00+00:00
[2024-11-06T19:47:15.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2931) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T19:47:15.251+0000] {standard_task_runner.py:72} INFO - Started process 2947 to run task
[2024-11-06T19:47:15.252+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '594', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmpnbt7jkfb']
[2024-11-06T19:47:15.256+0000] {standard_task_runner.py:105} INFO - Job 594: Subtask create_postgres_table
[2024-11-06T19:47:15.368+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [running]> on host 4b5a50a11bce
[2024-11-06T19:47:16.020+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sumit kumar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-11-06T19:47:16.022+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T19:47:16.024+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T19:47:16.025+0000] {logging_mixin.py:190} INFO - Current task name:create_postgres_table state:running start_date:2024-11-06 19:47:15.164994+00:00
[2024-11-06T19:47:16.027+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-11-06T19:47:16.029+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T19:47:16.031+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE if not exists Orders (
                OrderID INT PRIMARY KEY,
                Status VARCHAR(50)
            )
        
[2024-11-06T19:47:16.085+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_local` isn't defined
[2024-11-06T19:47:16.105+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-06T19:47:16.107+0000] {logging_mixin.py:190} INFO - Task start:2024-11-06 19:47:15.164994+00:00 end:2024-11-06 19:47:16.103530+00:00 duration:0.938536
[2024-11-06T19:47:16.109+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_postgres_table> dag:<DAG: dag_with_postgres_operator> dagrun:<DagRun dag_with_postgres_operator @ 2024-05-10 00:00:00+00:00: scheduled__2024-05-10T00:00:00+00:00, state:running, queued_at: 2024-11-06 19:47:09.522093+00:00. externally triggered: False>
[2024-11-06T19:47:16.110+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres_local` isn't defined
[2024-11-06T19:47:16.111+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20241106T194715, end_date=20241106T194716
[2024-11-06T19:47:16.147+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T19:47:16.148+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 594 for task create_postgres_table (The conn_id `postgres_local` isn't defined; 2947)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 166, in _hook
    hook = self.get_hook(conn_id=conn_id, hook_params=self.hook_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 158, in get_hook
    connection = BaseHook.get_connection(conn_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_local` isn't defined
[2024-11-06T19:47:16.199+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-06T19:47:16.218+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-07T20:10:18.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T20:10:18.560+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-07T20:10:18.575+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-07T20:10:18.576+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-07T20:10:18.601+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-05-10 00:00:00+00:00
[2024-11-07T20:10:18.614+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=508) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-07T20:10:18.618+0000] {standard_task_runner.py:72} INFO - Started process 520 to run task
[2024-11-07T20:10:18.619+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '705', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmp1sayp1rg']
[2024-11-07T20:10:18.622+0000] {standard_task_runner.py:105} INFO - Job 705: Subtask create_postgres_table
[2024-11-07T20:10:18.703+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [running]> on host 3f85553e814e
[2024-11-07T20:10:19.302+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sumit kumar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-11-07T20:10:19.304+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-07T20:10:19.305+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-07T20:10:19.306+0000] {logging_mixin.py:190} INFO - Current task name:create_postgres_table state:running start_date:2024-11-07 20:10:18.561368+00:00
[2024-11-07T20:10:19.307+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-11-07T20:10:19.307+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-07T20:10:19.308+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE if not exists Orders (
                OrderID INT PRIMARY KEY,
                Status VARCHAR(50)
            )
        
[2024-11-07T20:10:19.322+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-11-07T20:10:19.343+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-11-07T20:10:19.363+0000] {sql.py:544} INFO - Running statement: 
            CREATE TABLE if not exists Orders (
                OrderID INT PRIMARY KEY,
                Status VARCHAR(50)
            )
        , parameters: None
[2024-11-07T20:10:19.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-07T20:10:19.393+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20241107T201018, end_date=20241107T201019
[2024-11-07T20:10:19.479+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-07T20:10:19.480+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-07T20:10:19.481+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-11-07 20:10:14.386995+00:00
[2024-11-07T20:10:19.482+0000] {logging_mixin.py:190} INFO - Task hostname:3f85553e814e operator:PostgresOperator
[2024-11-07T20:10:19.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-07T20:10:19.579+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-07T20:10:19.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-09T20:52:13.290+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-09T20:52:13.349+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-09T20:52:13.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-11-09T20:52:13.429+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-09T20:52:13.515+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-05-10 00:00:00+00:00
[2024-11-09T20:52:13.543+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3087) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-09T20:52:13.549+0000] {standard_task_runner.py:72} INFO - Started process 3105 to run task
[2024-11-09T20:52:13.558+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '762', '--raw', '--subdir', 'DAGS_FOLDER/postgres.py', '--cfg-path', '/tmp/tmp1zk3pto9']
[2024-11-09T20:52:13.567+0000] {standard_task_runner.py:105} INFO - Job 762: Subtask create_postgres_table
[2024-11-09T20:52:13.802+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table scheduled__2024-05-10T00:00:00+00:00 [running]> on host 7a581205cd28
[2024-11-09T20:52:14.766+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sumit kumar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-11-09T20:52:14.769+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-09T20:52:14.771+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-09T20:52:14.778+0000] {logging_mixin.py:190} INFO - Current task name:create_postgres_table state:running start_date:2024-11-09 20:52:13.352127+00:00
[2024-11-09T20:52:14.783+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-11-09T20:52:14.786+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-09T20:52:14.792+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE if not exists Orders (
                OrderID INT PRIMARY KEY,
                Status VARCHAR(50)
            )
        
[2024-11-09T20:52:14.830+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-11-09T20:52:14.854+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-11-09T20:52:14.888+0000] {sql.py:544} INFO - Running statement: 
            CREATE TABLE if not exists Orders (
                OrderID INT PRIMARY KEY,
                Status VARCHAR(50)
            )
        , parameters: None
[2024-11-09T20:52:14.946+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-09T20:52:14.948+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, run_id=scheduled__2024-05-10T00:00:00+00:00, execution_date=20240510T000000, start_date=20241109T205213, end_date=20241109T205214
[2024-11-09T20:52:15.057+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-09T20:52:15.072+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-09T20:52:15.073+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-11-09 20:52:07.604618+00:00
[2024-11-09T20:52:15.073+0000] {logging_mixin.py:190} INFO - Task hostname:7a581205cd28 operator:PostgresOperator
[2024-11-09T20:52:15.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-09T20:52:15.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
